
GET https://example.com/comments/1
####
GET https://jsonkeeper.com/b/IYU1/

#####
//comments here super nice 
POST http://51.89.254.12:3000/api/v1/login HTTP/1.1
content-type: application/json

{
    "username": "1000",
    "password": "3454"
}

####